/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.LogicaEliminar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergi
 */
public class VentanaEliminar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminar
     */
    public VentanaEliminar() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDNIField = new javax.swing.JTextField();
        jEliminarButton = new javax.swing.JButton();
        jAtrasButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBuscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jValorPersona = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI:");

        jDNIField.setText("Insertar DNI");

        jEliminarButton.setText("Eliminar");
        jEliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarButtonActionPerformed(evt);
            }
        });

        jAtrasButton.setText("Atrás");
        jAtrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtrasButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("ELIMINAR DNI");

        jBuscarButton.setText("Buscar");
        jBuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarButtonActionPerformed(evt);
            }
        });

        jValorPersona.setColumns(20);
        jValorPersona.setRows(5);
        jScrollPane1.setViewportView(jValorPersona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDNIField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBuscarButton))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jAtrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jEliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jDNIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAtrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAtrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtrasButtonActionPerformed

        //
        this.dispose();
        VentaPrincipal vPrincipal = new VentaPrincipal();
        vPrincipal.setVisible(true);


    }//GEN-LAST:event_jAtrasButtonActionPerformed

    private void jBuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarButtonActionPerformed
        // TODO add your handling code here:

        if (LogicaEliminar.buscarPersona(jDNIField.getText())) {
            jValorPersona.setText("Nombre: " + LogicaEliminar.getPersonaEncontrada().getNombre()
                    + "\nApellido: " + LogicaEliminar.getPersonaEncontrada().getApellido() + "\nEdad: "
                    + LogicaEliminar.getPersonaEncontrada().getEdad() + "\nSexo: "
                    + LogicaEliminar.getPersonaEncontrada().getSexo()
            );

        }


    }//GEN-LAST:event_jBuscarButtonActionPerformed

    private void jEliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarButtonActionPerformed
        // TODO add your handling code here:
        LogicaEliminar.eliminarPersona();
        JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente");


    }//GEN-LAST:event_jEliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtrasButton;
    private javax.swing.JButton jBuscarButton;
    private javax.swing.JTextField jDNIField;
    private javax.swing.JButton jEliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jValorPersona;
    // End of variables declaration//GEN-END:variables

}
