/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.LogicaInicio;

/**
 *
 * @author Sergi
 */
public class VentaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentaPrincipal
     */
    public VentaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jNombreField = new javax.swing.JTextField();
        jApellidoField = new javax.swing.JTextField();
        jDNIField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSexoComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Trabajando = new javax.swing.JRadioButton();
        Estudiando = new javax.swing.JRadioButton();
        EnParo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombreField.setText("jTextField1");
        getContentPane().add(jNombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jApellidoField.setText("jTextField2");
        getContentPane().add(jApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jDNIField3.setText("jTextField3");
        getContentPane().add(jDNIField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jSexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        getContentPane().add(jSexoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        buttonGroup1.add(Trabajando);
        Trabajando.setText("Trabajando");
        getContentPane().add(Trabajando, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        buttonGroup1.add(Estudiando);
        Estudiando.setText("Estudiando");
        Estudiando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiandoActionPerformed(evt);
            }
        });
        getContentPane().add(Estudiando, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        buttonGroup1.add(EnParo);
        EnParo.setText("En Paro");
        getContentPane().add(EnParo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudiandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudiandoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        LogicaInicio.obtenerNombre(jNombreField.getText());
        LogicaInicio.obtenerApellido(jApellidoField.getText());
        LogicaInicio.obtenerDNI(jDNIField3.getText());
        LogicaInicio.obtenerGenero(jSexoComboBox.getSelectedItem().toString());
        LogicaInicio.obtenerEstado(buttonGroup1.getSelection().getActionCommand());
       // LogicaInicio.tratarCheckbox(buttonGroup1);

        LogicaInicio.guardarTXT();
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        jNombreField.setText("");
        jApellidoField.setText("");
        jDNIField3.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_limpiarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EnParo;
    private javax.swing.JRadioButton Estudiando;
    private javax.swing.JButton Guardar;
    private javax.swing.JRadioButton Trabajando;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jApellidoField;
    private javax.swing.JTextField jDNIField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNombreField;
    private javax.swing.JComboBox<String> jSexoComboBox;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
