/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Sergi
 */
public class VentanaModificar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDNIField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNombreField = new javax.swing.JTextField();
        jApellidoField = new javax.swing.JTextField();
        jEdadField = new javax.swing.JTextField();
        jSexoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonCNombre = new javax.swing.JButton();
        jBApellido = new javax.swing.JButton();
        jBEdad = new javax.swing.JButton();
        jBSexo = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DNI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        jDNIField.setText("DNI de la persona a modificar");
        getContentPane().add(jDNIField, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 21, 200, -1));

        jButton1.setText("Buscar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Apellido: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Sexo: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setText("Edad: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(jNombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, -1));
        getContentPane().add(jApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 90, -1));
        getContentPane().add(jEdadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, -1));
        getContentPane().add(jSexoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, -1));

        jLabel6.setText("Valories actuales:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButtonCNombre.setText("Cambiar Nombre");
        getContentPane().add(jButtonCNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jBApellido.setText("Cambiar Apellido");
        getContentPane().add(jBApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jBEdad.setText("Cambiar Edad");
        getContentPane().add(jBEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, -1));

        jBSexo.setText("Cambiar Sexo");
        getContentPane().add(jBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jBAtras.setText("Atrás");
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jApellidoField;
    private javax.swing.JButton jBApellido;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBEdad;
    private javax.swing.JButton jBSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCNombre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jDNIField;
    private javax.swing.JTextField jEdadField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNombreField;
    private javax.swing.JTextField jSexoField;
    // End of variables declaration//GEN-END:variables
}
